name = "neutronstar"
main = "@astrojs/cloudflare/entrypoints/server"
compatibility_date = "2025-08-19"
compatibility_flags = ["nodejs_compat"]

# 自定义域名路由
routes = [
  { pattern = "blog.neutronstar.fun/*", zone_name = "neutronstar.fun" }
]

# Cloudflare D1 数据库（后台写入、前端请求时读取）
d1_databases = [
  { binding = "DB", database_name = "neutronstar", database_id = "c76b53ae-c3c5-47a4-a696-9037a9b14c6f" }
]
